#!  /usr/bin/env bash
### ############################################################################
##! @file       ~/.xsession
##! @brief      Sources the gpg-agent-wrapper on X session start
##! @author     0xD62EE11516877AA8
##! @date       2016-09-17
##! @copyright  GPLv3+

source ${HOME}/.gnupg/help/gpg-agent-wrapper.sh

### end .xsession
### ############################################################################
